apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vod-ms-app-devices
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: vod-ms-app-devices
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70